export const REGISTER_USER = "REGISTER_USER";
export const ADD_PROJECT = "ADD_PROJECT";
export const APPLY_FOR_PROJECT = "APPLY_FOR_PROJECT";
export const CANCEL_APPLICATION = "CANCEL_APPLICATION";
export const DELETE_PROJECT = "DELETE_PROJECT";
